use crate::config::{Config, Desktop};
use anyhow::Result;
use std::path::Path;

/// The curated niri desktop: compositor, greeter, launcher, bar,
/// notifications, terminal, audio, portals, fonts.
const NIRI_PACKAGES: &[&str] = &[
    "niri",
    "xwayland-satellite",
    "greetd",
    "tuigreet",
    "fuzzel",
    "waybar",
    "mako",
    "alacritty",
    "pipewire",
    "pipewire-pulseaudio",
    "wireplumber",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-gnome",
    "gnome-keyring",
    "polkit",
    "mesa-dri-drivers",
    "default-fonts-core-sans",
    "default-fonts-core-mono",
];

const GREETD_CONFIG: &str = r#"[terminal]
vt = 1

[default_session]
command = "tuigreet --time --remember --cmd niri-session"
user = "greetd"
"#;

/// Desktop kernel args. The minimal base ships no auditd, so kernel audit
/// records spray onto the console; `quiet` keeps the console clean without
/// disabling auditing (records still reach the journal).
const DESKTOP_KARGS: &str = "kargs = [\"quiet\"]\n";

/// Compile a kuma config into a Containerfile for a bootc image build.
pub fn generate(config: &Config) -> String {
    let mut out = String::new();
    out.push_str("# Generated by kuma — edit kuma.toml instead.\n");
    out.push_str(&format!("FROM {}\n", config.system.base));

    // Desktop layer first: it is large and changes rarely, so keeping it
    // before the user's packages preserves the build cache across edits.
    if config.system.desktop == Desktop::Niri {
        out.push_str(&format!(
            "\nRUN dnf -y install {} && dnf clean all\n",
            NIRI_PACKAGES.join(" ")
        ));
        out.push_str("COPY greetd-config.toml /etc/greetd/config.toml\n");
        out.push_str("COPY kargs-desktop.toml /usr/lib/bootc/kargs.d/10-kuma-desktop.toml\n");
        out.push_str(
            "RUN systemctl set-default graphical.target && systemctl enable greetd.service\n",
        );
    }

    if !config.packages.rpm.is_empty() {
        out.push_str(&format!(
            "\nRUN dnf -y install {} && dnf clean all\n",
            config.packages.rpm.join(" ")
        ));
    }

    let services: Vec<String> = config
        .services
        .enable
        .iter()
        .map(|s| format!("systemctl enable {s}"))
        .chain(
            config
                .services
                .disable
                .iter()
                .map(|s| format!("systemctl disable {s}")),
        )
        .collect();
    if !services.is_empty() {
        out.push_str(&format!("\nRUN {}\n", services.join(" && ")));
    }

    out.push_str("\nRUN bootc container lint\n");
    out
}

/// Write the full build context: the Containerfile plus any files it COPYs.
pub fn write_context(config: &Config, dir: &Path) -> Result<()> {
    std::fs::write(dir.join("Containerfile"), generate(config))?;
    if config.system.desktop == Desktop::Niri {
        std::fs::write(dir.join("greetd-config.toml"), GREETD_CONFIG)?;
        std::fs::write(dir.join("kargs-desktop.toml"), DESKTOP_KARGS)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config(toml: &str) -> Config {
        let config: Config = toml::from_str(toml).unwrap();
        config.validate().unwrap();
        config
    }

    #[test]
    fn minimal_config_is_just_base_and_lint() {
        let out = generate(&config("schema_version = 1"));
        assert!(out.contains("FROM quay.io/fedora/fedora-bootc:44"));
        assert!(!out.contains("dnf"));
        assert!(out.contains("bootc container lint"));
    }

    #[test]
    fn full_config_generates_all_sections() {
        let out = generate(&config(
            r#"
            schema_version = 1
            [system]
            base = "ghcr.io/example/kuma-gnome:latest"
            [packages]
            rpm = ["fish", "tailscale"]
            [services]
            enable = ["tailscaled.service"]
            disable = ["cups.service"]
            "#,
        ));
        assert!(out.contains("FROM ghcr.io/example/kuma-gnome:latest"));
        assert!(out.contains("RUN dnf -y install fish tailscale && dnf clean all"));
        assert!(out.contains("systemctl enable tailscaled.service"));
        assert!(out.contains("systemctl disable cups.service"));
    }

    #[test]
    fn niri_desktop_generates_curated_layer() {
        let out = generate(&config(
            "schema_version = 1\n[system]\ndesktop = \"niri\"\n",
        ));
        assert!(out.contains("niri"));
        assert!(out.contains("greetd"));
        assert!(out.contains("COPY greetd-config.toml /etc/greetd/config.toml"));
        assert!(out.contains("systemctl set-default graphical.target"));
        assert!(out.contains("systemctl enable greetd.service"));
    }

    #[test]
    fn no_desktop_means_no_desktop_layer() {
        let out = generate(&config("schema_version = 1"));
        assert!(!out.contains("greetd"));
        assert!(!out.contains("graphical.target"));
    }

    #[test]
    fn desktop_layer_precedes_user_packages() {
        let out = generate(&config(
            "schema_version = 1\n[system]\ndesktop = \"niri\"\n[packages]\nrpm = [\"htop\"]\n",
        ));
        let desktop_at = out.find("niri").unwrap();
        let user_at = out.find("htop").unwrap();
        assert!(desktop_at < user_at);
    }

    #[test]
    fn context_includes_greetd_config_for_niri() {
        let dir = tempfile::tempdir().unwrap();
        write_context(
            &config("schema_version = 1\n[system]\ndesktop = \"niri\"\n"),
            dir.path(),
        )
        .unwrap();
        assert!(dir.path().join("Containerfile").exists());
        let greetd = std::fs::read_to_string(dir.path().join("greetd-config.toml")).unwrap();
        assert!(greetd.contains("niri-session"));
        let kargs = std::fs::read_to_string(dir.path().join("kargs-desktop.toml")).unwrap();
        assert!(kargs.contains("quiet"));
    }
}
