use crate::config::Config;

/// Compile a kuma config into a Containerfile for a bootc image build.
pub fn generate(config: &Config) -> String {
    let mut out = String::new();
    out.push_str("# Generated by kuma — edit kuma.toml instead.\n");
    out.push_str(&format!("FROM {}\n", config.system.base));

    if !config.packages.rpm.is_empty() {
        out.push_str(&format!(
            "\nRUN dnf -y install {} && dnf clean all\n",
            config.packages.rpm.join(" ")
        ));
    }

    let services: Vec<String> = config
        .services
        .enable
        .iter()
        .map(|s| format!("systemctl enable {s}"))
        .chain(
            config
                .services
                .disable
                .iter()
                .map(|s| format!("systemctl disable {s}")),
        )
        .collect();
    if !services.is_empty() {
        out.push_str(&format!("\nRUN {}\n", services.join(" && ")));
    }

    out.push_str("\nRUN bootc container lint\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config(toml: &str) -> Config {
        let config: Config = toml::from_str(toml).unwrap();
        config.validate().unwrap();
        config
    }

    #[test]
    fn minimal_config_is_just_base_and_lint() {
        let out = generate(&config("schema_version = 1"));
        assert!(out.contains("FROM quay.io/fedora/fedora-bootc:44"));
        assert!(!out.contains("dnf"));
        assert!(out.contains("bootc container lint"));
    }

    #[test]
    fn full_config_generates_all_sections() {
        let out = generate(&config(
            r#"
            schema_version = 1
            [system]
            base = "ghcr.io/example/kuma-gnome:latest"
            [packages]
            rpm = ["fish", "tailscale"]
            [services]
            enable = ["tailscaled.service"]
            disable = ["cups.service"]
            "#,
        ));
        assert!(out.contains("FROM ghcr.io/example/kuma-gnome:latest"));
        assert!(out.contains("RUN dnf -y install fish tailscale && dnf clean all"));
        assert!(out.contains("systemctl enable tailscaled.service"));
        assert!(out.contains("systemctl disable cups.service"));
    }
}
