//! Installing kuma onto a disk.
//!
//! The account is the whole difficulty. A published image declares no
//! `[user]`, because the image is shared and the person is not, so a
//! machine installed from one has no account and no root password and no
//! way in. Anaconda's create-a-user screen used to cover that, and live
//! media has no Anaconda.
//!
//! So the installer's real output is a declaration. It asks, writes
//! `/etc/kuma/user` on the target, and `kuma-user-sync` creates the
//! account at first boot exactly as it does for a declared one. The
//! installer does not create users; it writes down what the machine
//! should converge to, which is the same thing kuma does everywhere else.
//!
//! Getting that file onto the target needs no post-install mounting.
//! `bootc install` copies the filesystem of the container it runs inside,
//! so kuma derives a one-layer image carrying the file and installs from
//! that, while `--target-imgref` records the *published* image as what
//! the machine fetches for subsequent updates. The installed system
//! therefore has an account and still tracks the public tag.
//!
//! Scope is deliberately whole-disk. `bootc install to-disk` owns the
//! partitioning, so there is no cryptsetup here and no custom layout;
//! passphrase LUKS needs `to-filesystem` and kuma owning the storage,
//! which is a larger and much more dangerous piece of work. This verb is
//! the one that had to exist first, because without it a published image
//! installs to a machine nobody can log into.

use anyhow::{bail, Result};

/// What the person answered, and what the target will converge to.
pub struct Account {
    pub name: String,
    pub password_hash: String,
    pub groups: Vec<String>,
}

/// The file `kuma-user-sync` sources, in the format it already reads.
///
/// Deliberately the same shape as the baked `/usr/lib/kuma/user` rather
/// than a new one: the converger gains a second source, not a second
/// parser, and a machine installed this way is indistinguishable at boot
/// from one whose declaration named the account.
pub fn user_file(account: &Account) -> String {
    let mut out = format!("KUMA_USER='{}'\n", account.name);
    if !account.groups.is_empty() {
        out.push_str(&format!("KUMA_GROUPS='{}'\n", account.groups.join(" ")));
    }
    out.push_str(&format!("KUMA_PASSWORD_HASH='{}'\n", account.password_hash));
    out
}

/// The one-layer image that carries the account onto the target.
///
/// 0600 for the same reason the baked one is: it holds a password hash
/// and only the root-run converger reads it. This image is thrown away
/// once the install finishes; nothing tags it for keeping.
pub fn install_containerfile(source: &str) -> String {
    format!(
        "# Generated by kuma for `kuma install`. One layer over the image\n\
         # being installed, carrying the account the target converges to.\n\
         FROM {source}\n\
         COPY --chmod=600 kuma-user /etc/kuma/user\n"
    )
}

/// Reasons not to write to this disk, in the order a person would want
/// to hear them.
///
/// Pure over the mount table so the dangerous branch is testable without
/// a spare disk. Every other kuma verb is reversible: `switch` stages,
/// `rollback` exists, a bad build is a build. This one is not, so the
/// checks that stop it are the part worth being sure of.
pub fn disk_objections(disk: &str, proc_mounts: &str, lsblk_mountpoints: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut seen = std::collections::BTreeSet::new();
    if !disk.starts_with("/dev/") {
        out.push(format!("{disk} is not a device path"));
    }

    // lsblk first, because it is the only one that sees through LUKS and
    // LVM. /proc/mounts names the *mapper* device for an encrypted root,
    // so a disk whose every partition is inside a crypt container has no
    // line in it that mentions the disk at all. On a machine with /boot
    // encrypted too, a check built only on /proc/mounts finds nothing to
    // object to and cheerfully wipes the running system.
    for mount in lsblk_mountpoints.lines().map(str::trim).filter(|l| !l.is_empty()) {
        if seen.insert(mount.to_string()) {
            out.push(format!("something on {disk} is in use at {mount}"));
        }
    }

    // And /proc/mounts, which needs no external command: if lsblk is
    // missing or fails, this is the whole guard rather than none of it.
    // Matches /dev/sda1 for /dev/sda and /dev/nvme0n1p1 for /dev/nvme0n1.
    for line in proc_mounts.lines() {
        let mut fields = line.split_whitespace();
        let (Some(source), Some(target)) = (fields.next(), fields.next()) else {
            continue;
        };
        let is_partition = source == disk
            || source.strip_prefix(disk).is_some_and(|rest| {
                let rest = rest.strip_prefix('p').unwrap_or(rest);
                !rest.is_empty() && rest.chars().all(|c| c.is_ascii_digit())
            });
        if is_partition && seen.insert(target.to_string()) {
            out.push(format!("{source} from {disk} is mounted at {target}"));
        }
    }
    out
}

/// Ask for the account the target will create at first boot.
///
/// Piped stdin reads name and password as two lines, which keeps the
/// verb scriptable and keeps a password out of argv where `ps` would
/// show it. There is no `--password` flag for that reason.
pub fn ask_account(name: Option<String>, groups: Vec<String>) -> Result<Account> {
    use std::io::IsTerminal;
    let interactive = std::io::stdin().is_terminal();
    let name = match name {
        Some(name) => name,
        None if interactive => {
            eprint!("Account name for the installed machine: ");
            let mut line = String::new();
            std::io::stdin().read_line(&mut line)?;
            line.trim().to_string()
        }
        None => bail!("no account name: pass --user, or run this on a terminal"),
    };
    crate::config::validate_name(&name, "user.name", &['.', '-', '_'])?;

    let password = if interactive {
        let first = rpassword::prompt_password(format!("Password for {name}: "))?;
        let again = rpassword::prompt_password("Retype to confirm: ")?;
        if first != again {
            bail!("passwords don't match");
        }
        first
    } else {
        let mut line = String::new();
        std::io::stdin().read_line(&mut line)?;
        line.trim_end_matches(['\r', '\n']).to_string()
    };
    if password.is_empty() {
        bail!("empty password: the installed machine would have no way in");
    }
    Ok(Account { name, password_hash: crate::hash_password(&password)?, groups })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn account() -> Account {
        Account {
            name: "mira".into(),
            password_hash: "$6$abc$def".into(),
            groups: vec!["wheel".into()],
        }
    }

    /// The installer writes what the converger already reads. If these
    /// drift, an installed machine silently comes up with no account,
    /// which is the exact failure this verb exists to prevent.
    #[test]
    fn the_written_file_is_what_user_sync_sources() {
        let text = user_file(&account());
        assert!(text.contains("KUMA_USER='mira'"));
        assert!(text.contains("KUMA_GROUPS='wheel'"));
        assert!(text.contains("KUMA_PASSWORD_HASH='$6$abc$def'"));
        // Shell-sourceable: one KEY='value' per line, nothing else.
        for line in text.lines() {
            assert!(line.contains("='"), "not a shell assignment: {line}");
        }
    }

    /// A mounted partition of the target is the one thing between this
    /// verb and destroying the medium it is running from. On live media
    /// the ISO is mounted, and a person who typed the wrong letter would
    /// otherwise find out afterwards.
    #[test]
    fn a_mounted_partition_of_the_target_is_an_objection() {
        let mounts = "\
/dev/nvme0n1p3 / btrfs rw 0 0
/dev/nvme0n1p2 /boot ext4 rw 0 0
/dev/sr0 /run/initramfs/live iso9660 ro 0 0
tmpfs /tmp tmpfs rw 0 0
";
        let objections = disk_objections("/dev/nvme0n1", mounts, "");
        assert_eq!(objections.len(), 2, "both partitions of the target");

        // A different disk is not an objection just because it exists.
        assert!(disk_objections("/dev/sda", mounts, "").is_empty());
        // ... and the partition-suffix match must not fire on a disk
        // whose name merely starts the same way.
        assert!(disk_objections("/dev/nvme0", mounts, "").is_empty());
    }

    /// The case /proc/mounts cannot see, and the one most likely to be
    /// somebody's actual laptop: every partition inside a LUKS container,
    /// so the mount table names /dev/mapper/luks-... and never the disk.
    /// Without lsblk this disk looks idle and gets wiped while running.
    #[test]
    fn an_encrypted_disk_with_no_direct_mounts_is_still_in_use() {
        let mounts = "\
/dev/mapper/luks-f5d1fc89 /sysroot btrfs rw 0 0
/dev/mapper/luks-f5d1fc89 /var btrfs rw 0 0
";
        assert!(
            disk_objections("/dev/nvme0n1", mounts, "").is_empty(),
            "the mount table genuinely cannot see this, which is the point"
        );
        let lsblk = "/var\n/sysroot\n\n/boot\n";
        let objections = disk_objections("/dev/nvme0n1", mounts, lsblk);
        assert_eq!(objections.len(), 3, "blank lines are unmounted partitions");
        assert!(objections.iter().all(|o| o.contains("in use at")));
    }

    /// Both sources naming the same mount point is one objection, not two.
    #[test]
    fn the_two_sources_do_not_double_report() {
        let mounts = "/dev/sda1 /boot ext4 rw 0 0\n";
        let objections = disk_objections("/dev/sda", mounts, "/boot\n");
        assert_eq!(objections.len(), 1);
    }

    #[test]
    fn a_path_that_is_not_a_device_is_an_objection() {
        assert!(!disk_objections("nvme0n1", "", "").is_empty());
        assert!(!disk_objections("/home/me/disk.img", "", "").is_empty());
    }

    /// The account rides in as a layer rather than being written after
    /// the fact, and the installed machine still tracks the published
    /// image. Losing either half is silent: the first gives a machine
    /// with no account, the second a machine that can never update.
    #[test]
    fn the_derived_layer_carries_the_account_at_0600() {
        let out = install_containerfile("ghcr.io/example/kuma:niri");
        assert!(out.contains("FROM ghcr.io/example/kuma:niri"));
        assert!(out.contains("COPY --chmod=600 kuma-user /etc/kuma/user"));
    }
}
