//! kuma.lock: what the last build actually resolved.
//!
//! The declaration says `base = "quay.io/fedora/fedora-bootc:44"`, and
//! that tag moves under you. It moved bootc 1.16.6 to 1.16.7 between two
//! `kuma update` runs and broke every build on this machine, which is the
//! whole argument for a lockfile in one sentence.
//!
//! What is locked and what is merely recorded is a deliberate split:
//!
//! - **The base digest is enforced.** Builds resolve `FROM name@sha256:…`
//!   from here, so the same declaration plus the same lock builds from
//!   the same bytes on any machine, forever.
//! - **Package versions are recorded, not enforced.** Pinning rpm NVRAs
//!   would be worse than useless on a live Fedora: the mirrors garbage
//!   collect old builds within weeks, so a pinned version turns into a
//!   build failure that has nothing to do with your declaration, and
//!   transitive dependencies stay unpinned regardless. What the record is
//!   *for* is seeing what moved between two builds and bisecting when one
//!   of them broke, which needs no enforcement at all.
//!
//! There is no `kuma lock` verb. `kuma build` reads the pin and refreshes
//! the record; `kuma update` is the one thing that moves the pin, because
//! moving it deliberately is what `kuma update` already meant.

use crate::host::host_output;
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

pub const CURRENT_SCHEMA: u32 = 1;

#[derive(Serialize, Deserialize)]
pub struct Lock {
    pub schema_version: u32,
    /// When the record was taken. Informational: nothing reads it back,
    /// but a lockfile that can't tell you how old it is is annoying.
    pub locked_at: String,
    pub base: Base,
    pub resolved: Resolved,
}

#[derive(Serialize, Deserialize)]
pub struct Base {
    /// The declaration's `system.base`, verbatim. Kept so a changed
    /// declaration can be told apart from a moved tag: the first means
    /// the pin is for a different image entirely and must be re-resolved.
    #[serde(rename = "ref")]
    pub reference: String,
    pub digest: String,
}

#[derive(Serialize, Deserialize)]
pub struct Resolved {
    /// name -> EVR.arch for everything in the built image. A map rather
    /// than a list of NVRAs, so it sorts by package name and a version
    /// bump is a one-line git diff instead of a delete plus an add.
    pub rpm: BTreeMap<String, String>,
}

/// Flatpaks and brew formulae are deliberately absent. They aren't
/// resolved at build time at all: convergence installs them on the
/// machine at first boot and every day after, so anything recorded here
/// would be a build-host guess describing a system nobody is running.
/// The image records the declared *lists* already; the versions belong to
/// the machine, which is the same acknowledged mutable edge `kuma
/// capture` works on.
const _: () = ();

impl Lock {
    /// Absent is normal (first build, fresh checkout), and so is
    /// unreadable: a corrupt lock must never block a build, because the
    /// next build regenerates it anyway.
    pub fn load(path: &Path) -> Option<Lock> {
        let text = std::fs::read_to_string(path).ok()?;
        match toml::from_str::<Lock>(&text) {
            Ok(lock) if lock.schema_version == CURRENT_SCHEMA => Some(lock),
            Ok(lock) => {
                eprintln!(
                    "{} has schema_version {} (this kuma writes {}); ignoring it",
                    path.display(),
                    lock.schema_version,
                    CURRENT_SCHEMA
                );
                None
            }
            Err(err) => {
                eprintln!("{} is unreadable ({err}); rebuilding it", path.display());
                None
            }
        }
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let body = toml::to_string_pretty(self).context("cannot serialize the lock")?;
        let text = format!(
            "# Generated by kuma. Do not edit.\n\
             # The base digest is what builds actually use; the resolved\n\
             # package versions are a record to diff, not pins to install.\n\
             # `kuma update` is what moves this file.\n\n{body}"
        );
        std::fs::write(path, text).with_context(|| format!("cannot write {}", path.display()))
    }

    /// `name@sha256:…` for the declaration's base, or None when this lock
    /// describes a different one (the declaration was edited, so the
    /// declaration wins and the pin gets re-resolved).
    pub fn pin_for(&self, declared: &str) -> Option<String> {
        (self.base.reference == declared).then(|| pinned_ref(declared, &self.base.digest))
    }
}

/// `quay.io/fedora/fedora-bootc:44` + digest -> `quay.io/fedora/fedora-bootc@sha256:…`
///
/// The tag has to go: `name:tag@digest` is legal for some tools and
/// rejected by others, and the digest is the only part that decides what
/// gets pulled anyway. Splitting on the LAST colon after the last slash
/// keeps a registry port (`localhost:5000/x`) from being read as a tag.
pub fn pinned_ref(reference: &str, digest: &str) -> String {
    let name = match reference.rsplit_once('/') {
        Some((host, last)) => match last.split_once(':') {
            Some((repo, _tag)) => format!("{host}/{repo}"),
            None => reference.to_string(),
        },
        None => match reference.split_once(':') {
            Some((repo, _tag)) => repo.to_string(),
            None => reference.to_string(),
        },
    };
    format!("{name}@{digest}")
}

pub fn path_for(config_path: &Path) -> PathBuf {
    config_path.with_extension("lock")
}

/// The manifest digest of a base image already in local storage, which is
/// where it is right after a build that used it. No extra pull.
pub fn base_digest(reference: &str) -> Result<String> {
    let out = host_output(&["podman", "image", "inspect", "--format", "{{.Digest}}", reference])?;
    let digest = out.trim().to_string();
    anyhow::ensure!(digest.starts_with("sha256:"), "unexpected digest {digest:?} for {reference}");
    Ok(digest)
}

/// Everything the built image ended up containing. Asking the image
/// beats asking dnf: this is what shipped, including whatever arrived as
/// a dependency of something else.
pub fn resolved_rpms(tag: &str) -> Result<BTreeMap<String, String>> {
    let out = host_output(&[
        "podman", "run", "--rm", tag, "rpm", "-qa", "--qf", "%{NAME} %{EVR}.%{ARCH}\\n",
    ])?;
    Ok(parse_rpm_query(&out))
}

/// rpm's own field separator, so no NVRA guessing: package names contain
/// dashes (python3-dbus) and splitting one apart by hand gets it wrong.
fn parse_rpm_query(out: &str) -> BTreeMap<String, String> {
    out.lines()
        .filter_map(|line| line.trim().split_once(' '))
        .map(|(name, evr)| (name.to_string(), evr.to_string()))
        .collect()
}

/// What moved between two builds.
pub struct LockDiff {
    pub base_from: String,
    pub base_to: String,
    /// name, old version, new version
    pub changed: Vec<(String, String, String)>,
    pub added: Vec<String>,
    pub removed: Vec<String>,
}

impl LockDiff {
    pub fn is_empty(&self) -> bool {
        self.base_from == self.base_to
            && self.changed.is_empty()
            && self.added.is_empty()
            && self.removed.is_empty()
    }
}

pub fn diff(old: &Lock, new: &Lock) -> LockDiff {
    let mut changed = Vec::new();
    let mut added = Vec::new();
    for (name, version) in &new.resolved.rpm {
        match old.resolved.rpm.get(name) {
            Some(before) if before != version => {
                changed.push((name.clone(), before.clone(), version.clone()))
            }
            Some(_) => {}
            None => added.push(name.clone()),
        }
    }
    let removed = old
        .resolved
        .rpm
        .keys()
        .filter(|name| !new.resolved.rpm.contains_key(*name))
        .cloned()
        .collect();
    LockDiff {
        base_from: old.base.digest.clone(),
        base_to: new.base.digest.clone(),
        changed,
        added,
        removed,
    }
}

/// Take the record after a successful build and write it beside the
/// declaration. Never fatal: a build that produced an image succeeded,
/// and /usr/lib/kuma is read-only when the declaration came from the
/// image itself.
pub fn record(config_path: &Path, declared_base: &str, built_from: &str, tag: &str) -> Option<Lock> {
    let digest = match base_digest(built_from) {
        Ok(digest) => digest,
        Err(err) => {
            eprintln!("cannot resolve the base digest ({err}); no lock written");
            return None;
        }
    };
    let rpm = match resolved_rpms(tag) {
        Ok(rpm) => rpm,
        Err(err) => {
            eprintln!("cannot read the image's package list ({err}); no lock written");
            return None;
        }
    };
    let lock = Lock {
        schema_version: CURRENT_SCHEMA,
        locked_at: utc_now(),
        base: Base { reference: declared_base.to_string(), digest },
        resolved: Resolved { rpm },
    };
    let path = path_for(config_path);
    if let Err(err) = lock.save(&path) {
        eprintln!("{err:#}; continuing without a lock");
        return None;
    }
    Some(lock)
}

fn utc_now() -> String {
    let secs = SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_secs()).unwrap_or(0);
    rfc3339(secs)
}

/// Seconds since the epoch as `YYYY-MM-DDTHH:MM:SSZ`. Hand-rolled
/// (civil-from-days) rather than adding a date crate for one timestamp
/// nothing parses back.
fn rfc3339(secs: u64) -> String {
    let (days, rem) = ((secs / 86_400) as i64, secs % 86_400);
    // Howard Hinnant's civil_from_days, with the era shifted so day 0 is
    // 1970-01-01.
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z.rem_euclid(146_097);
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    format!(
        "{y:04}-{m:02}-{d:02}T{:02}:{:02}:{:02}Z",
        rem / 3600,
        (rem % 3600) / 60,
        rem % 60
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn lock(digest: &str, rpms: &[(&str, &str)]) -> Lock {
        Lock {
            schema_version: CURRENT_SCHEMA,
            locked_at: "2026-08-07T00:00:00Z".into(),
            base: Base {
                reference: "quay.io/fedora/fedora-bootc:44".into(),
                digest: digest.into(),
            },
            resolved: Resolved {
                rpm: rpms.iter().map(|(n, v)| (n.to_string(), v.to_string())).collect(),
            },
        }
    }

    /// The tag has to come off: `name:tag@digest` is accepted by some
    /// tools and rejected by others, and a registry port must not be
    /// mistaken for one.
    #[test]
    fn pinning_replaces_the_tag_and_survives_a_registry_port() {
        let d = "sha256:abc";
        assert_eq!(
            pinned_ref("quay.io/fedora/fedora-bootc:44", d),
            "quay.io/fedora/fedora-bootc@sha256:abc"
        );
        assert_eq!(
            pinned_ref("quay.io/fedora/fedora-bootc", d),
            "quay.io/fedora/fedora-bootc@sha256:abc"
        );
        assert_eq!(pinned_ref("localhost:5000/kuma:44", d), "localhost:5000/kuma@sha256:abc");
        assert_eq!(pinned_ref("fedora-bootc:44", d), "fedora-bootc@sha256:abc");
    }

    /// A lock pins the base it was taken for. Editing `system.base` in
    /// the declaration means the pin describes a different image, and the
    /// declaration is the truth, so the pin is dropped rather than
    /// silently building the old base.
    #[test]
    fn a_pin_only_applies_to_the_base_it_was_taken_for() {
        let lock = lock("sha256:abc", &[]);
        assert_eq!(
            lock.pin_for("quay.io/fedora/fedora-bootc:44").as_deref(),
            Some("quay.io/fedora/fedora-bootc@sha256:abc")
        );
        assert!(lock.pin_for("quay.io/fedora/fedora-bootc:45").is_none());
        assert!(lock.pin_for("ghcr.io/someone/else:44").is_none());
    }

    /// rpm's space separator, because package names contain dashes and
    /// splitting an NVRA by hand puts half of python3-dbus in the version.
    #[test]
    fn rpm_names_with_dashes_survive_parsing() {
        let parsed = parse_rpm_query(
            "fish 4.0.2-1.fc44.x86_64\npython3-dbus 1.4.0-3.fc44.x86_64\n\n",
        );
        assert_eq!(parsed.get("fish").unwrap(), "4.0.2-1.fc44.x86_64");
        assert_eq!(parsed.get("python3-dbus").unwrap(), "1.4.0-3.fc44.x86_64");
        assert_eq!(parsed.len(), 2);
    }

    #[test]
    fn diff_separates_a_version_bump_from_an_arrival() {
        let old = lock("sha256:old", &[("bootc", "1.16.6-1.fc44.x86_64"), ("gone", "1-1")]);
        let new = lock("sha256:new", &[("bootc", "1.16.7-1.fc44.x86_64"), ("new", "1-1")]);
        let d = diff(&old, &new);
        assert_eq!(d.base_from, "sha256:old");
        assert_eq!(d.base_to, "sha256:new");
        assert_eq!(d.changed, [("bootc".into(), "1.16.6-1.fc44.x86_64".into(), "1.16.7-1.fc44.x86_64".into())]);
        assert_eq!(d.added, ["new"]);
        assert_eq!(d.removed, ["gone"]);
        assert!(!d.is_empty());
    }

    #[test]
    fn an_unmoved_base_with_identical_packages_is_no_change() {
        let a = lock("sha256:same", &[("fish", "4.0.2-1.fc44.x86_64")]);
        let b = lock("sha256:same", &[("fish", "4.0.2-1.fc44.x86_64")]);
        assert!(diff(&a, &b).is_empty());
    }

    /// Round-trips through the file, because a lock nobody can read back
    /// is just a slow way to rebuild from the tag.
    #[test]
    fn a_written_lock_reads_back() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("kuma.lock");
        lock("sha256:abc", &[("fish", "4.0.2-1.fc44.x86_64")]).save(&path).unwrap();
        let text = std::fs::read_to_string(&path).unwrap();
        assert!(text.starts_with("# Generated by kuma. Do not edit."));
        let back = Lock::load(&path).unwrap();
        assert_eq!(back.base.digest, "sha256:abc");
        assert_eq!(back.resolved.rpm["fish"], "4.0.2-1.fc44.x86_64");
    }

    /// Absent, corrupt, and from-the-future all mean the same thing to a
    /// build: no pin, carry on, write a fresh one afterward.
    #[test]
    fn an_unusable_lock_never_blocks_a_build() {
        let dir = tempfile::tempdir().unwrap();
        let missing = dir.path().join("nope.lock");
        assert!(Lock::load(&missing).is_none());

        let corrupt = dir.path().join("corrupt.lock");
        std::fs::write(&corrupt, "this is not toml {{{").unwrap();
        assert!(Lock::load(&corrupt).is_none());

        let future = dir.path().join("future.lock");
        std::fs::write(
            &future,
            "schema_version = 99\nlocked_at = \"x\"\n[base]\nref = \"a\"\ndigest = \"b\"\n[resolved.rpm]\n",
        )
        .unwrap();
        assert!(Lock::load(&future).is_none());
    }

    #[test]
    fn timestamps_are_rfc3339_utc() {
        assert_eq!(rfc3339(0), "1970-01-01T00:00:00Z");
        assert_eq!(rfc3339(1_770_000_000), "2026-02-02T02:40:00Z");
        // a leap day, because the calendar arithmetic is hand-rolled
        assert_eq!(rfc3339(1_709_164_800), "2024-02-29T00:00:00Z");
    }

    #[test]
    fn the_lock_sits_beside_its_declaration() {
        assert_eq!(path_for(Path::new("kuma.toml")), Path::new("kuma.lock"));
        assert_eq!(
            path_for(Path::new("examples/cosmic.kuma.toml")),
            Path::new("examples/cosmic.kuma.lock")
        );
    }
}
